%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1408
image_height: 370
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 552.554261
   fy: 552.554261
   cx: 682.049453
   cy: 238.769549
